### ISSUE TITLE
SQLite support is broken

### ISSUE THREAD

**Issue by Cirras** [ethanmoffat/etheos#25]
**Background**
* EOSERV does all of its database operations in one big transaction on the main thread.
* SQLite only supports one simultaneous write transaction.

**Problem**
* Since the addition of asynchronous database operations on background threads for the `LoginManager`, SQLite support has been broken.

**Reproduction case**
* Configure EOSERV to use an SQLite database
* Create an account
* Account creation will fail, and a `Database_QueryFailed` exception will be raised.
* The error message from SQLite is "database is locked"

**See**
* [World::BeginDB](https://github.com/ethanmoffat/etheos/blob/58bb2a4428ebbbcbfc00cc2a79009ea7a7f5d276/src/world.cpp#L535)
* [SQLite: Transaction](https://www.sqlite.org/lang_transaction.html)

**Comment by ethanmoffat** [comment]
Thanks for this, easy repro. I'll start working on a solution.

FYI setting `TimedSave=0m` in the configuration seems to work around it. I'll be focusing on improving that functionality so the db doesn't constantly have an open pending transaction.

**Comment by Cirras** [comment]
I assume this issue is fixed since https://github.com/ethanmoffat/etheos/commit/12302ec34d6fd81bb83674157d02c6d48025d742?
Is there any other obvious work to be done in this area?

**Comment by ethanmoffat** [comment]
Oh you're right - I forgot about this issue since I've been tracking tasks on clickup.
