### ISSUE TITLE
Add Azure CI pipelines

### ISSUE THREAD

**Issue by iandinwoodie** [ethanmoffat/etheos#7]
Add Windows and Linux Azure CI pipelines.

**Comment by iandinwoodie** [comment]
## MariaDB Warning

Is the following [MariaDB warning](https://ethanmoffat.visualstudio.com/EndlessClient/_build/results?buildId=281&view=logs&j=db7f412c-f65b-523f-50f9-7d9022009b89&t=fba59f01-b271-5d99-c78c-d8a9c09c394f&l=21) typical with your Windows development workflow?

```txt
WARNING: Warning: no MariaDB found in $env:PATH - CMake may not be able to find the dependency
```

## Link Errors

You may be aware of this already, but I would guess that all of the [`LNK2019` errors](https://ethanmoffat.visualstudio.com/EndlessClient/_build/results?buildId=281&view=logs&j=db7f412c-f65b-523f-50f9-7d9022009b89&t=fba59f01-b271-5d99-c78c-d8a9c09c394f&l=87):

```txt
system.obj : error LNK2019: unresolved external symbol _mysql_num_rows@4 referenced in function __catch$?RawQuery@Database@@QAE?AVDatabase_Result@@PBD_N1@Z$0 [D:\a\1\s\build\eoserv.vcxproj]
...
system.obj : error LNK2019: unresolved external symbol _mysql_close@4 referenced in function "public: void __thiscall Database::Close(void)" (?Close@Database@@QAEXXZ) [D:\a\1\s\build\eoserv.vcxproj]
```

are a result of the [`LNK4272` error](https://ethanmoffat.visualstudio.com/EndlessClient/_build/results?buildId=281&view=logs&j=db7f412c-f65b-523f-50f9-7d9022009b89&t=fba59f01-b271-5d99-c78c-d8a9c09c394f&l=104):

```txt
C:\mysql-5.7.21-winx64\lib\mysqlclient.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86' [D:\a\1\s\build\eoserv.vcxproj]
```

Where we can see the discrepancy between the 32-bit compiler and 64-bit library arise in the following two CMake output lines:

```txt
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x86/cl.exe
...
-- Found MariaDB: C:/mysql-5.7.21-winx64/lib/mysqlclient.lib 
```

I don't have a solution, because I'm not sure how the pipeline fetches that mysqlclient library. Just wanted to pitch in what I could on the troubleshooting.

**Comment by iandinwoodie** [comment]
The warnings in the ["Install build dependencies"](https://ethanmoffat.visualstudio.com/EndlessClient/_build/results?buildId=281&view=logs&j=db7f412c-f65b-523f-50f9-7d9022009b89&t=3c81fd72-7bd5-50eb-04d5-ca953abaa5d3&l=15) and ["Build"](https://ethanmoffat.visualstudio.com/EndlessClient/_build/results?buildId=281&view=logs&j=db7f412c-f65b-523f-50f9-7d9022009b89&t=fba59f01-b271-5d99-c78c-d8a9c09c394f&l=21) jobs seem to go hand-in-hand:

```txt
WARNING: Warning: libmariadb.dll not found in $env:PATH
```

```txt
WARNING: Warning: no MariaDB found in $env:PATH - CMake may not be able to find the dependency
```

And it seems like we are expecting to use `libmariadb.dll` but [CMake is using `mysqlclient.lib`](https://ethanmoffat.visualstudio.com/EndlessClient/_build/results?buildId=281&view=logs&j=db7f412c-f65b-523f-50f9-7d9022009b89&t=fba59f01-b271-5d99-c78c-d8a9c09c394f&l=64):

```txt
-- Found MariaDB: C:/mysql-5.7.21-winx64/lib/mysqlclient.lib
```

So, it seems like we are installing a specific MariaDB library, but CMake is using a different library to satisfy that dependency?

**Comment by ethanmoffat** [comment]
Yeah, I think this has to do with MySql client connector being pre-installed on the Azure Pipelines VMs. And apparently it has been built for x64 which is frustrating since eoserv isn't designed to build that way. We're in a catch 22 with the build:

- Force 32-bit mode to make eoserv build properly causes linker errors with MySQL because its x64
- Force 64-bit mode to fix linker errors causes build to fail because we need 32-bit

I think I'm going to build out my own VM for Windows builds and just have it target that, but that will take a hot minute so please stand by :)

**Comment by ethanmoffat** [comment]
Finished in #26 

There's a "hints" option for `find_library` that lets you specify a path to the library, so that kept it from picking up the 64-bit version of mysql that is installed on the build VMs.
